version: "3.9"
services:
  server:
    image: 'server'
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
# client:
#    container_name: client
#    build:
#      context: ./client
#    ports:
#      - 3000:3000
#    depends_on:
#      server:
#	  condition: service_healthy


